version: '3'

services:
  app:
    build: .
    depends_on:
      - db
      - kafka
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 26257
      DATABASE_USER: root
      DATABASE_NAME: tradedb
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  db:
    image: cockroachdb/cockroach:v19.2.2
    ports:
        - "26257:26257"
        - "8080:8080"
    command: start-single-node --insecure
    volumes:
        - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
        - zookeeper
    ports:
        - 29092:29092
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_ADVERTISED_HOST_NAME: kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    ports:
        - 22181:2181
